### ISSUE TITLE
Добавить модуль и базовую структуру файла конфигурации

### ISSUE THREAD

**Issue by ShestakovDA** [ShestakovDA/warlog#1]
Сабтаски:
- [x] #13 формат связки строк

Предусмотреть следующие секции:

* Настройка HTTP API
* Настройка подключений к различным БД
* Импорт файлов конфигурации источников
* Внутреннее логирование, каталоги, прочие параметры
* Версионирование используемых интерфейсов и плагины

Формат - YAML

В Wiki включить описание всех полей и примеры настройки

Частично обсуждается в #7

**Comment by voledemar** [comment]
Уточнения от @ShestakovDA про пятый пункт:

> Это один из пунктов задачи про конфигурацию. Предполагается, что 1) код будет версионироваться, для последовательного внесения изменений без потери обратной совместимости. Т.е. например напишем мы парсер конфигурации v1. Он будет работать, но мы захотим что-то улучшить - и напишем рядом парсер v2. А в конфиге нужно управлять, какую версию какого модуля подключаем.  и 2) сторонние разработчики будут писать плагины, модули или обработчики событий. Нужно продумать, как их подключать - и как это указывать в конфиге

**Comment by voledemar** [comment]
Предварительный формат вместе с примером описаны [здесь](https://github.com/ShestakovDA/warlog/wiki/%D0%9A%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D1%83%D1%80%D0%B0%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B9-%D1%84%D0%B0%D0%B9%D0%BB).

**Comment by voledemar** [comment]
@ShestakovDA, требуется одобрение.

**Comment by voledemar** [comment]
Сделать разделение output на storage и output (collections).

**Comment by voledemar** [comment]
В конфиге параметр - с начала строки или с самого себя брать новый объект (в дополнение к задаче #7).

**Comment by voledemar** [comment]
Разработка ведётся в ветке `feature/config`.

**Comment by ShestakovDA** [comment]
Устарела
