### ISSUE TITLE
Настроить интеграцию с Travis CI

### ISSUE THREAD

**Issue by voledemar** [ShestakovDA/warlog#14]
Короче, т.к. пул-реквеста не было, опишу тут. Решил добавить менеджерские штуки в виде Travis'а и CodeCov, чтобы всегда было видно, какая ситуация в девелоп-ветке.

Только тебе нужно будет зайти со своего ГитХаб-аккаунта в Трэвис и включить запуск джобов. Там просто чек-бокс щёлкнуть. Настройки по-умолчанию должны подойти.

Если это не нужно, то выпилю. Но думаю, что полезненько, особенно для тебя, как менеджера. :)

**Comment by ShestakovDA** [comment]
Авторизовал использование, проверим, что работает, тогда закрою

**Comment by voledemar** [comment]
Закрываю, реализовано.
