### ISSUE TITLE
Добавить парсер и валидатор файла конфигурации 

### ISSUE THREAD

**Issue by ShestakovDA** [ShestakovDA/warlog#2]
Согласно статье Wiki по задаче #1 реализовать парсер конфига

- [ ] Глобально видимый интерфейс
- [ ] #12 Валидация параметров
- [ ] Возможность перезагрузки "на лету" с проверкой и откатом
- [ ] Явно обозначить версию парсера в названии типов и файлов
- [ ] Unit-тесты с покрытием не менее 70%

**Comment by voledemar** [comment]
Создал ветку `feature/config` для данной задачи.
