### ISSUE TITLE
Добавить базовый класс для работы с PostgreSQL

### ISSUE THREAD

**Issue by ShestakovDA** [ShestakovDA/warlog#5]
* При реализации учитывать строение абстрактного типа из задачи #3
  - Использовать только стандартные database/sql и pq
* Продумать использование структуры и типов PG, автоматизации запросов
* Продумать возможные механизмы буферизации записи
* Продумать возможные механизмы автоматической индексации частых поисковых запросов
* Описать все идеи в Wiki

**Comment by PavelEfimov** [comment]
по механизму буферизации записи:
C задачи номер 3 нам приходит абстрактный тип данных . Есть некий список(в частности карта), представленный в виде  map[string]interface{}, ключ представляет из себя  целое число. В списке проходит проверка: если количество элементов превышает 5000, то наш список мы обнуляем и все элементы записываем в базу. Также существует проверка, что если в течении 5 минут не поступит новых записей, ты выгружаем наш список в базу данных.  Наши данные будут храниться сериализованными в формате json в нашей базе. Индексацию на наиболее частые запросы можно организовать  с помощью таблицы логов, где  по выборке наиболее частых поисковых запросов, можно будет установить на этот запрос индекс
