### ISSUE TITLE
Спроектировать правила описания парсера текстовых логов

### ISSUE THREAD

**Issue by ShestakovDA** [ShestakovDA/warlog#7]
* Все идеи описывать в Wiki
* Придумать, как использовать регулярные выражения
* Спроектировать, как концептуально должен работать парсер

Подзадачи:
- [ ] Доки / тесты #20

**Comment by ShestakovDA** [comment]
Есть предложение использовать формат yaml для конфигурации парсера тестовых логов. Имею следующие соображения:

* Парсером будем считать функцию, которая принимает на вход исходный текст и шаблон в виде регулярного выражения, а на выходе дает некоторый объект, который можно сериализовать в json
* Поскольку json - это нотация описания объектов, она подойдет и для описания способа получения объектов
* Поскольку json можно по сути считать частным случаем yaml - последний даст более широкие возможности в будущем
* Основные файлы конфигурации также используют yaml с возможностью импорта - проект будет более единообразным и простым в настройке
* С помощью yaml также можно естественным образом организовать каталогизацию и переиспользование шаблонов, объявлять вложенные структуры
* Основный принцип посторения шаблона - пары ключ/значение. Ключ - имя целевого поля в объекте. Значение - строка регулярного выражения
* Регулярка для парсера складывается в процессе "компиляции" файла конфигурации. Компиляцией в этом контексте будем считать формирование единой строки регулярного выражения, которая будет применяться к исходному тексту, функции с правилами сопоставления шаблона и поля объекта, а также функции-генератора новых объектов.

Пока не придумал, как решить проблему частей строк, которые не являются целевыми. Например:

Строка: 1245.24 
Нужно получить объект с двумя полями: целой и дробной частью
Возможная регулярка: (\d{1,8})\.(\d{2})
Возможный конфиг объекта:

```yaml
item:
    base: "\\d{1,8}"
    frac: "\\d{2}"
```

Вопрос - как указать разделитель точку между полями, чтобы она не являлась частью объекта

**Comment by voledemar** [comment]
@ShestakovDA, а не лучше тогда придумать свой формат? Что-то типа:

`<\d{1,8}>[base].<\d{2}>[frac]`

* В `<>` указывается регулярка.
* Следом в `[]` указывается имя поля, в которое складывать.
* Всё остальное игнорируется.

Но выбрать символы, с которыми не придётся возиться из-за проблем с экранированием.

**Comment by voledemar** [comment]
Отбраковынные логи можно складывать в какую-нибудь отдельную таблицу, по которой тоже производить поиск, если пользователь захочет.

К слову, есть [вот такая штука - Heka](https://hekad.readthedocs.io/en/v0.10.0/) (я уже кидал [ссылку на хабр](https://habrahabr.ru/company/yamoney/blog/328018/), где она описывалась). Работает с плагинами на Go. Но этот проект заброшен ([вот их репа](https://github.com/mozilla-services/heka)). Насколько я понял, их наработки перекочевали на [вот эту Сишную репу](https://github.com/mozilla-services/hindsight).

**Comment by voledemar** [comment]
Входной массив байт - последовательность объектов, каждый из которых имеет **символ начала (предикат)** (пользователь задаёт в конфиге). Парсить по началу нового символа начала.

Последний объект (часть) сохраняем в буфер и ждём следующей пачки массива байт.

**Comment by voledemar** [comment]
@DiKey98, создай в wiki новую страницу и опиши, всё, что решено на данный момент

**Comment by voledemar** [comment]
[Создана страница wiki][wiki] с описнием особенностей данной задачи.

[wiki]: https://github.com/ShestakovDA/warlog/wiki/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0%D1%82-%D0%BA%D0%BE%D0%BD%D1%84%D0%B8%D0%B3%D0%B0-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%BE%D0%B2-%D0%BB%D0%BE%D0%B3%D0%B0

**Comment by voledemar** [comment]
Я тут подумал: разделитель между объектами нужно описывать регуляркой, т.к. он может содержать динамические данные, которые мы просто не хотим включать в результат.

Например:

```log
64.242.88.10 - - [07/Mar/2004:16:05:49 -0800] "GET /twiki/bin/edit/Main/Double_bounce_sender?topicparent=Main.ConfigurationVariables HTTP/1.1" 401 12846
64.242.88.10 - - [07/Mar/2004:16:06:51 -0800] "GET /twiki/bin/rdiff/TWiki/NewUserTemplate?rev1=1.3&rev2=1.2 HTTP/1.1" 200 4523
```

* Имя поля: IP
  * Разделитель: ` - - [` (с пробелом пробелом первым символом)
  * Регулярка: `((25[0-5]|2[0-4]\d|[01]?\d\d?)\.){3}(25[0-5]|2[0-4]\d|[01]?\d\d?)`
* Имя поля: Date
  * Разделитель: `] ` (с пробелом пробелом последним символом)
  * Регулярка: `(\d{2})\/(\w{3})\/(\d{4}):(\d{2}):(\d{2}):(\d{2})`
* Имя поля Url:
  * Разделитель: ` ` (пробел)
  * Регулярка: `@^(https?|ftp)://[^\s/$.?#].[^\s]*$@iS`

А вот метод (GET, POST и т.д.) нам не нужен. Ну, хотим мы так. Это можно описать регуляркой.

**Comment by voledemar** [comment]
[Wiki-страница][wiki] переименована и обновлена.

[Wiki]: https://github.com/ShestakovDA/warlog/wiki/%D0%A4%D0%BE%D1%80%D0%BC%D0%B0%D1%82-%D0%BB%D0%BE%D0%B3%D0%B0

**Comment by annakhl** [comment]
Нужно сделать модуль в ООП стиле (поместить все в структуру).

**Comment by annakhl** [comment]
И надо написать тесты, понятно!
