### ISSUE TITLE
Спроектировать формат отправки/получения данных по сети  

### ISSUE THREAD

**Issue by ShestakovDA** [ShestakovDA/warlog#8]
* Записать результат в Wiki
* Учесть возможность кластерной обработки одного проекта
* Продумать сетевое обнаружение и конфигурацию
* Минимизировать накладные расходы
* Продумать буферизацию

**Comment by voledemar** [comment]
Погуглить `protobuf`, `JSON RPC`.

Покурить [этот пакет](https://golang.org/pkg/net/rpc/).

**Comment by voledemar** [comment]
Хорошие ссылки:

* [О протобуффере](https://developers.google.com/protocol-buffers/docs/overview)
* [О RPC в перспективе Go](http://haisum.github.io/2015/10/13/rpc-jsonrpc-gorilla-example-in-golang/)
