### ISSUE TITLE
Спроектировать файловый источник данных

### ISSUE THREAD

**Issue by ShestakovDA** [ShestakovDA/warlog#9]
* Придумать, как реализовать последовательное чтение источника
* Предусмотреть возможность замены источника на лету
* Предусмотреть возможность изменения дескриптора файла
* Результат записывать в Wiki

**Comment by Slava12** [comment]
Создана функция по чтению файла ReadFile, принимает на вход имя файла, возвращает буфер и число прочитанных байт. Содержимое считывается в буфер. Затем ищется в нём крайний символ конца строки, всё что следует после него обнуляется. Позиция чтения смещается на полученное количество байт.
Эта функция вызывается в функции ProcessFile. Она представляет собой бесконечный цикл, в котором через каждый промежуток времени, заданный таймером, происходит непрерывное чтение до тех пор, пока буфер не перестанет заполняться полностью.

**Comment by Slava12** [comment]
Нужно добавить объект FileReader. В нём должна присутствовать работа с каналами (go channel). В функции main будет инициализирован конструктор данного объекта с параметрами из конфига. Должна присутствовать функция по созданию нового канала. Внутри объекта работает функция ProcessFile, её внутренняя ReadFile должна отправлять полученный буфер в канал. Также необходимо предусмотреть множественное чтение из канала. Ещё должна быть функция "Получить канал".
